newest things

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -22,17 +22,16 @@ awscmd() {
 
 check_app() {
   if [[ -z "$APP" ]]; then
-    echo "Please specify an <app name>"
+    echo "Error: Please specify an <app name>"
     exit 1
   fi
-  [[ ! -d "$DOKKU_ROOT/$APP" ]] && echo "App $APP does not exist!" && exit 1
+  [[ ! -d "$DOKKU_ROOT/$APP" ]] && echo "Error: App $APP does not exist!" && exit 1
   echo
 }
 
 check_already_exists() {
   if [[ -f "$APP_KEY_FILE" ]]; then
-    echo "App: $APP already has AWS Keys tored in file $APP_KEY_FILE!"
-    echo "Quitting."
+    echo "Info: App $APP already has AWS Keys stored in file $APP_KEY_FILE!"
     exit 1
   fi
   echo
@@ -40,8 +39,7 @@ check_already_exists() {
 
 ensure_exists() {
   if [[ ! -f "$APP_KEY_FILE" ]]; then
-    echo "There are no stored credentials for App: $APP. Create them with dokku aws_keys:create $APP."
-    echo "Quitting."
+    echo "Error: There are no stored credentials for App: $APP. Create them with dokku aws_keys:create $APP"
     exit 1
   fi
   echo
@@ -49,16 +47,17 @@ ensure_exists() {
 
 load_root_keys() {
   if ! source $HOME/root_keys; then
-    echo "Damn!!!! Configure the root keys with aws_keys:configure"
+    echo "Error: Please Configure AWS Root keys with: dokku aws_keys:configure <aws_id> <aws_secret>"
     exit 1
   fi
-  echo "Loaded Root keys"
+  echo "Using stored root keys"
 }
 
 ensure_aws_group_exists() {
-  if ! awscmd iam get-group --group-name $GROUPNAME; then
-    echo "$GROUPNAME doesnt exist!"
-    if awscmd iam create-group --group-name $GROUPNAME; then
+  echo "Info: Esnure the existence of group $GROUPNAME ..."
+  if ! output=$(awscmd iam get-group --group-name ${GROUPNAME}) ; then
+    echo "Info: $GROUPNAME doesnt exist. Creating it now...."
+    if output=$(awscmd iam create-group --group-name ${GROUPNAME}); then
       echo "Created group $GROUPNAME"
     else
       echo "Damn, I fail. Crap."
@@ -71,7 +70,7 @@ ensure_aws_group_exists() {
 
 
 ensure_aws_user_exists() {
-  if ! awscmd iam create-user --user-name $USERNAME; then
+  if ! output=$(awscmd iam create-user --user-name ${USERNAME}); then
     echo "User: $USERNAME already exist!"
   else
     echo "User: $USERNAME created!"
@@ -79,7 +78,7 @@ ensure_aws_user_exists() {
 }
 
 ensure_aws_user_membership_in_group() {
-  if ! awscmd iam add-user-to-group --user-name $USERNAME --group-name $GROUPNAME; then
+  if ! ouput=$(awscmd iam add-user-to-group --user-name ${USERNAME} --group-name ${GROUPNAME}); then
     echo "Membership: User $USERNAME is alread in Group $GROUPNAME!"
   else
     echo "Membership: User $USERNAME added to Group $GROUPNAME!"
@@ -92,8 +91,7 @@ case "$1" in
     ensure_exists
     AWS_ACCESS_KEY_ID=$(perl -ne 'print "$1" if /"AccessKeyId": "(.*)"/' ${APP_KEY_FILE})
     AWS_SECRET_ACCESS_KEY=$(perl -ne 'print "$1" if /"SecretAccessKey": "(.*)"/' ${APP_KEY_FILE})
-    echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
-    echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
+    echo "-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
     ;;
 
   aws_keys:rm)
@@ -122,7 +120,6 @@ case "$1" in
     echo "export AWS_SECRET_ACCESS_KEY=$3" >> $HOME/root_keys
     echo "export AWS_DEFAULT_REGION=us-west-1" >> $HOME/root_keys
     ;;
-
 
   aws_keys:create)
 
